### ISSUE TITLE
Tool doesn't work

### ISSUE THREAD

**Issue by Piergi20** [mmohan01/MultiRefactor#1]
I've installed your tool to try see the effectiveness of it on my project. However, when I go to run `MultiRefactor.bat` and see it at work, it gives several number of UnresolvedReferenceException, even if I try to run it as default on the json-1.1 source code. The JDK is included in the build path of the project

### Expected Behavior
The tool should work

###  Actual Behavior
`*** 2: UnresolvedReferenceException
Could not resolve TypeReference "java.util.List(id 25)" @8/8 in FILE:C:\path\MultiRefactor\.\data\json-1.1\main\java\org\json\simple\ItemList.java(14)

*** 3: UnresolvedReferenceException
Could not resolve TypeReference "java.util.StringTokenizer(id 33)" @9/8 in FILE:FILE:C:\path\MultiRefactor\.\data\json-1.1\main\java\org\json\simple\ItemList.java(14)

*** 4: UnresolvedReferenceException
Could not resolve TypeReference "String(id 41)" @18/13 in FILE:C:\path\MultiRefactor\.\data\json-1.1\main\java\org\json\simple\ItemList.java(14)

*** 5: UnresolvedReferenceException
Could not resolve TypeReference "List(id 48)" @19/5 in FILE:C:\path\MultiRefactor\.\data\json-1.1\main\java\org\json\simple\ItemList.java(14)

*** 6: UnresolvedReferenceException
Could not resolve TypeReference "ArrayList(id 53)" @19/20 in FILE:C:\path\MultiRefactor\.\data\json-1.1\main\java\org\json\simple\ItemList.java(14)

*** 7: UnresolvedReferenceException
Could not resolve New "new ArrayList()(id 50)" @19/16 in FILE:C:\path\MultiRefactor\.\data\json-1.1\main\java\org\json\simple\ItemList.java (05)

*** 8: UnresolvedReferenceException
Could not resolve TypeReference "String(id 65)" @25/21 in FILE:C:\path\MultiRefactor\.\data\json-1.1\main\java\org\json\simple\ItemList.java(14)

*** 9: UnresolvedReferenceException
Could not resolve TypeReference "String(id 179)" @46/23 in FILE:C:\path\MultiRefactor\.\data\json-1.1\main\java\org\json\simple\ItemList.java(14)

*** 10: UnresolvedReferenceException
Could not resolve TypeReference "String(id 185)" @46/32 in FILE:C:\path\MultiRefactor\.\data\json-1.1\main\java\org\json\simple\ItemList.java(14)

*** 11: UnresolvedReferenceException
Could not resolve TypeReference "List(id 191)" @46/42 in FILE:C:\path\MultiRefactor\.\data\json-1.1\main\java\org\json\simple\ItemList.java(14)

*** 12: UnresolvedReferenceException
Could not resolve TypeReference "String(id 271)" @60/23 in FILE:C:\path\MultiRefactor\.\data\json-1.1\main\java\org\json\simple\ItemList.java(14)

*** 13: UnresolvedReferenceException
Could not resolve TypeReference "String(id 277)" @60/32 in FILE:C:\path\MultiRefactor\.\data\json-1.1\main\java\org\json\simple\ItemList.java(14)

*** 14: UnresolvedReferenceException
Could not resolve TypeReference "List(id 283)" @60/42 in FILE:C:\path\MultiRefactor\.\data\json-1.1\main\java\org\json\simple\ItemList.java(14)

*** 15: UnresolvedReferenceException
Could not resolve TypeReference "String(id 391)" @76/23 in FILE:C:\path\MultiRefactor\.\data\json-1.1\main\java\org\json\simple\ItemList.java(14)

*** 16: UnresolvedReferenceException
Could not resolve TypeReference "String(id 414)" @80/27 in FILE:C:\path\MultiRefactor\.\data\json-1.1\main\java\org\json\simple\ItemList.java(14)

*** 17: UnresolvedReferenceException
Could not resolve TypeReference "String(id 445)" @86/21 in FILE:C:\path\MultiRefactor\.\data\json-1.1\main\java\org\json\simple\ItemList.java(14)

*** 18: UnresolvedReferenceException
Could not resolve TypeReference "String(id 495)" @96/24 in FILE:C:\path\MultiRefactor\.\data\json-1.1\main\java\org\json\simple\ItemList.java(14)

*** 19: UnresolvedReferenceException
Could not resolve TypeReference "String(id 517)" @100/24 in FILE:C:\path\MultiRefactor\.\data\json-1.1\main\java\org\json\simple\ItemList.java(14)

*** 20: UnresolvedReferenceException
Could not resolve TypeReference "String(id 523)" @100/33 in FILE:C:\path\MultiRefactor\.\data\json-1.1\main\java\org\json\simple\ItemList.java(14)

*** 21: UnresolvedReferenceException
Could not resolve TypeReference "String(id 545)" @104/24 in FILE:C:\path\MultiRefactor\.\data\json-1.1\main\java\org\json\simple\ItemList.java(14)

21 errors have occured - aborting.
Exception in thread "main" recoder.service.TooManyErrorsException: 21 errors have occured - aborting.
        at recoder.service.DefaultErrorHandler.exitAction(DefaultErrorHandler.java:126)
        at recoder.service.DefaultErrorHandler.reportError(DefaultErrorHandler.java:137)
        at recoder.service.DefaultSourceInfo.getType(DefaultSourceInfo.java:910)
        at recoder.service.DefaultSourceInfo.getType(DefaultSourceInfo.java:1001)
        at recoder.service.DefaultSourceInfo.getSignature(DefaultSourceInfo.java:2691)
        at recoder.java.declaration.MethodDeclaration.getSignature(MethodDeclaration.java:790)
        at recoder.service.DefaultProgramModelInfo.computeAllMethods(DefaultProgramModelInfo.java:273)
        at recoder.service.DefaultProgramModelInfo.getAllMethods(DefaultProgramModelInfo.java:245)
        at recoder.java.declaration.TypeDeclaration.getAllMethods(TypeDeclaration.java:494)
        at recoder.service.DefaultProgramModelInfo.getMethods(DefaultProgramModelInfo.java:1245)
        at recoder.service.DefaultSourceInfo.getMethods(DefaultSourceInfo.java:2240)
        at recoder.service.DefaultSourceInfo.getMethod(DefaultSourceInfo.java:2144)
        at recoder.service.DefaultCrossReferenceSourceInfo.analyzeReferences(DefaultCrossReferenceSourceInfo.java:616)
        at recoder.service.DefaultCrossReferenceSourceInfo.modelChanged(DefaultCrossReferenceSourceInfo.java:229)
        at recoder.service.ChangeHistory.updateModel(ChangeHistory.java:501)
        at multirefactor.Metrics.numberOfHierarchies(Metrics.java:84)
        at multirefactor.FitnessFunction.<init>(FitnessFunction.java:31)
        at searches.RandomSearch.run(RandomSearch.java:43)
        at tasks.Tasks.run(Tasks.java:166)
        at multirefactor.Main.main(Main.java:50)`

### Step to reproduce
MultiRefactor.bat

**Comment by mmohan01** [comment]
This tool isn't being maintained or supported. However, the posted errors look to be getting encountered by the underlying [RECODER library](https://sourceforge.net/projects/recoder/) that the MultiRefactor tool utilises to modify the Java source code.


There are some older posts on their forum ([here](https://sourceforge.net/p/recoder/discussion/88904/thread/81787fee/#ef14), [here](https://sourceforge.net/p/recoder/discussion/88905/thread/447533b8/?limit=25#b493)) that mention the tendency of the RECODER library to raise these exceptions when attempting to analyse Java code.
It may be useful to investigate the usage of the RECODER library and see if this can be avoided or managed.

**Comment by Piergi20** [comment]
Thanks for the reply. I will take a glimpse to the forums to understand better the issue and manage it
